name: Tests
on: push

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        
        - name: Setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.11.3
 
        - name: Install tools
          run: python -m pip install
               --upgrade pip pytest

        - name: Install other tools
          run: pip install -r requirements.txt

        - name: Install pandas
          run: pip install pandas

        - name: Test with unittest
          run: python3 -m unittest app.tests